version: '3'
services:
  webserver:
    container_name: webserver${NAME_PPREFIX}
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Apache.DockerFile
      args:
        - 'INSTALL_MC=${INSTALL_MC}'
        - 'INSTALL_SSH=${INSTALL_SSH}'
        - 'INSTALL_GIT=${INSTALL_GIT}'
        - 'INSTALL_XDEBUG=${INSTALL_XDEBUG}'
        - 'INSTALL_CRON=${INSTALL_CRON}'
        - 'INSTALL_SUPERVISOR=${INSTALL_SUPERVISOR}'
        - 'USER=${APACHE2_OS_USER}'
        - 'PW=${APACHE2_OS_PASSWORD}'
        - 'INSTALL_TYPE=${APACHE2_VOLUME_INSTALL_TYPE}'
        - 'ROOT_PW=${APACHE2_OS_ROOT_PASSWORD}'
    ports:
      - '${APACHE2_HTTP_PORT}:80'
      - '${APACHE2_HTTPS_PORT}:443'
      - '${SSH_PORT}:22'
    restart: always
    volumes:
      - '${APACHE2_VOLUME}:/.${APACHE2_VOLUME_INSTALL_TYPE:-/var/www/localhost}'
  mariadb:
    container_name: mariadb${NAME_PPREFIX}
    image: mariadb
    restart: always
    stdin_open: true
    tty: true
    command: '--max_allowed_packet=32505856'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD}'
    ports:
      - '${MYSQL_PORT}:3306'
    expose:
      - '3306'
    volumes:
      - '${MYSQL_VOLUME}:/var/lib/mysql'
  phpmyadmin:
    container_name: phpmyadmin${NAME_PPREFIX}
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      UPLOAD_LIMIT: 3000000000
  laravel-echo-server:
    container_name: laravel-echo-server${NAME_PPREFIX}
    build:
      context: ./
      dockerfile: LaravelEchoServer.DockerFile
    ports:
      - '${ECHO_SERVER_PORT}:6001'
    depends_on:
      - redis
    restart: always
  redis:
    container_name: redis${NAME_PPREFIX}
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - "6379"
